-- Indexes on the foreign keys the service layer reads as lookup keys.
--
-- Generated by drizzle-kit from the schema declarations; the reasoning
-- for the set is here so the next person does not have to reconstruct it.
--
-- PostgreSQL indexes the parent side of a foreign key automatically and
-- the child side never. An audit of pg_constraint found 38 child columns
-- with no supporting index. This adds the 15 the code actually filters
-- on, not all 38 — an index no query uses is a write cost and a page of
-- disk for nothing.
--
-- Measured before adding, on a synthetic 200 000-row thread_messages
-- table (the shape that grows fastest — one row per message, forever):
--
--   without: Parallel Seq Scan, 100 201 rows discarded, 2 713 buffers, 17.7 ms
--   with:    Bitmap Index Scan, 1 buffer, 0.385 ms
--
-- 46x, and the gap widens linearly with row count. At today's volumes
-- the planner ignores most of these because the tables fit in a page or
-- two; that is fine. They exist so the first busy month is not what
-- discovers them.
--
-- Deliberately NOT indexed: the provenance columns — created_by,
-- reviewed_by, moderated_by, uploaded_by, assigned_to, dispatched_by.
-- Written on every mutation, read only when someone opens one record's
-- history. Indexing them taxes every write to speed up a query nobody
-- runs in a loop.

CREATE INDEX "idx_agreement_signatures_signer" ON "agreement_signatures" USING btree ("signed_by_user_id");--> statement-breakpoint
CREATE INDEX "idx_agreements_company" ON "agreements" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_capacity_listings_company" ON "capacity_listings" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_companies_owner" ON "companies" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "idx_company_references_company" ON "company_references" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_company_slugs_company" ON "company_slugs" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_contacts_company" ON "contacts" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_portfolio_items_company" ON "portfolio_items" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_workers_company" ON "workers" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_thread_messages_thread_created" ON "thread_messages" USING btree ("thread_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_offer_team_members_offer" ON "offer_team_members" USING btree ("offer_id");--> statement-breakpoint
CREATE INDEX "idx_reviews_buyer" ON "reviews" USING btree ("buyer_user_id");--> statement-breakpoint
CREATE INDEX "idx_rfq_attachments_rfq" ON "rfq_attachments" USING btree ("rfq_id");--> statement-breakpoint
CREATE INDEX "idx_rfq_dispatches_rfq" ON "rfq_dispatches" USING btree ("rfq_id");--> statement-breakpoint
CREATE INDEX "idx_rfqs_buyer" ON "rfqs" USING btree ("buyer_user_id");