apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - postgres.yaml
  - minio.yaml
  - clamav.yaml
  - migrate-job.yaml
  - app.yaml
  - network-policy.yaml
  - ingress.yaml
